apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-uploads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi  # 900MB storage for all uploads
  storageClassName: default  # Use your cluster's default storage class